name: Xodium CI/CD

on:
  push:
    branches: [main]
    paths:
      - "irp/**"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.create_release.outputs.url }}
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}
      SHA1: ${{ steps.calculate_sha1.outputs.SHA1 }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - id: get_version
        name: Get Version
        run: echo "VERSION=$(jq -r '.version' version.json)" >> $GITHUB_OUTPUT

      - id: packsquash
        name: Create Zip & Optimize with Packsquash
        uses: ComunidadAylas/PackSquash-action@02b01307cac41fc9a4c92df3b03bca802625d7d1
        with:
          packsquash_version: latest-unstable
          options: |
            pack_directory = 'irp'
            output_file_path = 'irp_v${{ steps.get_version.outputs.VERSION }}.zip'

      - id: calculate_sha1
        name: Calculate SHA1
        run: echo "SHA1=$(sha1sum "irp_v${{ steps.get_version.outputs.VERSION }}.zip" | awk '{ print $1 }')" >> $GITHUB_OUTPUT

      - id: create_release
        name: Create Release
        uses: softprops/action-gh-release@5434409c2b6457c050f109d68b2547fcbf1db07b
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: ${{ contains(github.event.head_commit.message, '.draft') }}
          files: irp_v${{ steps.get_version.outputs.VERSION }}.zip
          body: |
            Direct Download Link: https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.VERSION }}/irp_${{ steps.get_version.outputs.VERSION }}.zip
            SHA-1 Hash: ${{ steps.calculate_sha1.outputs.SHA1 }}
          generate_release_notes: true
          prerelease: ${{ contains(github.event.head_commit.message, '.pre') }}
          tag_name: v${{ steps.get_version.outputs.VERSION }}

  deploy:
    name: Deploy
    needs: release
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    steps:
      - id: uspr
        name: Update server.properties remotely
        uses: appleboy/ssh-action@3ca8a7c5359ac6ad91aa47f1946ece1c3b025004
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          script: |
            sed -i \
              -e "s|^resource-pack=.*|resource-pack=https://github.com/${{ github.repository }}/releases/download/${{ needs.release.outputs.VERSION }}/irp_${{ needs.release.outputs.VERSION }}.zip|" \
              -e "s|^resource-pack-sha1=.*|resource-pack-sha1=${{ needs.release.outputs.SHA1 }}|" \
              ${{ secrets.SFTP_MCS_PROPERTIES_PATH }}
